/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_li3huo_util_CoreDumper */

#ifndef _Included_com_li3huo_util_CoreDumper
#define _Included_com_li3huo_util_CoreDumper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_li3huo_util_CoreDumper
 * Method:    core
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_li3huo_util_CoreDumper_core
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
