/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CoreDumper */

#ifndef _Included_CoreDumper
#define _Included_CoreDumper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CoreDumper
 * Method:    core
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_CoreDumper_core
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
